[package]
name = "rpgtool"
version = "0.1.0"
authors = ["Bartłomiej Kuras <hash.deb@gmail.com>"]

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
clap = "2.26.2"
maud = { version = "0.17.1", features = ["rocket"] }
